### ISSUE TITLE
Error on any request

### ISSUE THREAD

**Issue by tillvollmer** [chartmogul/chartmogul-ruby#56]
Hi,
Ruby 2.3.7
Faraday: 0.11.0

I am getting similar errors on any request in the API. Any ideas. Maybe some Faraday version problems?

```
ChartMogul::Ping.ping
ChartMogul::ChartMogulError: undefined method `retry_statuses=' for #<Faraday::Request::Retry::Options:0x00007fc4db982360>
	from /Users/tvollmer/.rvm/gems/ruby-2.3.7/gems/chartmogul-ruby-1.2.0/lib/chartmogul/api_resource.rb:76:in `handle_other_error'
	from /Users/tvollmer/.rvm/gems/ruby-2.3.7/gems/chartmogul-ruby-1.2.0/lib/chartmogul/api_resource.rb:47:in `rescue in handling_errors'
	from /Users/tvollmer/.rvm/gems/ruby-2.3.7/gems/chartmogul-ruby-1.2.0/lib/chartmogul/api_resource.rb:42:in `handling_errors'
	from /Users/tvollmer/.rvm/gems/ruby-2.3.7/gems/chartmogul-ruby-1.2.0/lib/chartmogul/api/actions/custom.rb:20:in `custom_without_assign!'
	from /Users/tvollmer/.rvm/gems/ruby-2.3.7/gems/chartmogul-ruby-1.2.0/lib/chartmogul/api/actions/custom.rb:30:in `custom!'
	from /Users/tvollmer/.rvm/gems/ruby-2.3.7/gems/chartmogul-ruby-1.2.0/lib/chartmogul/ping.rb:11:in `ping'
	from (irb):5
	from /Users/tvollmer/.rvm/gems/ruby-2.3.7/gems/railties-5.0.7.1/lib/rails/commands/console.rb:65:in `start'
	from /Users/tvollmer/.rvm/gems/ruby-2.3.7/gems/railties-5.0.7.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/tvollmer/.rvm/gems/ruby-2.3.7/gems/railties-5.0.7.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/tvollmer/.rvm/gems/ruby-2.3.7/gems/railties-5.0.7.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/tvollmer/.rvm/gems/ruby-2.3.7/gems/railties-5.0.7.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

```

**Comment by pkopac** [comment]
Hi, we had [a similar issue before](https://github.com/chartmogul/chartmogul-ruby/issues/52#issuecomment-419983457), so we introduced [this version requirement](https://github.com/chartmogul/chartmogul-ruby/blob/master/chartmogul-ruby.gemspec#L23).

Is it not working for you properly?

**Comment by tillvollmer** [comment]
Ha, thanks, I got 1.2.0 on bundle install, might be because some other dependencies. Thanks closing...
